"""Add starred, edited_at, reactions to messages

Revision ID: 4177e5bf2f21
Revises: fc37ea22d9bf
Create Date: 2025-07-01 12:26:16.277024

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4177e5bf2f21'
down_revision = 'fc37ea22d9bf'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'messages' in inspector.get_table_names():
        existing = {col["name"] for col in inspector.get_columns('messages')}
        if 'starred' not in existing:
            op.add_column('messages', sa.Column('starred', sa.Boolean(), nullable=True))
        if 'edited_at' not in existing:
            op.add_column('messages', sa.Column('edited_at', sa.DateTime(), nullable=True))
        if 'reactions' not in existing:
            op.add_column('messages', sa.Column('reactions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reactions')
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'starred')
    # ### end Alembic commands ###
