"""Add starred, edited_at, reactions to messages

Revision ID: 4177e5bf2f21
Revises: fc37ea22d9bf
Create Date: 2025-07-01 12:26:16.277024

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4177e5bf2f21'
down_revision = 'fc37ea22d9bf'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('starred', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('reactions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reactions')
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'starred')
    # ### end Alembic commands ###
