"""add last_typing_at to conversations

Revision ID: 9e7e0e35a411
Revises: 4177e5bf2f21
Create Date: 2025-07-01 13:36:51.368898

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9e7e0e35a411'
down_revision = '4177e5bf2f21'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    def table_exists(name: str) -> bool:
        return name in inspector.get_table_names()
    def has_column(table: str, column: str) -> bool:
        if not table_exists(table):
            return False
        return column in {col["name"] for col in inspector.get_columns(table)}
    def has_fk(table: str, columns: list, ref_table: str) -> bool:
        if not table_exists(table):
            return False
        for fk in inspector.get_foreign_keys(table):
            if fk.get("referred_table") == ref_table and fk.get("constrained_columns") == columns:
                return True
        return False

    if not has_column('conversations', 'last_typing_at'):
        op.add_column('conversations', sa.Column('last_typing_at', sa.DateTime(), nullable=True))
    if not has_column('messages', 'reply_to_id'):
        op.add_column('messages', sa.Column('reply_to_id', sa.Integer(), nullable=True))
    if not has_column('messages', 'seen_at'):
        op.add_column('messages', sa.Column('seen_at', sa.DateTime(), nullable=True))
    if table_exists('messages') and has_column('messages', 'reply_to_id') and not has_fk('messages', ['reply_to_id'], 'messages'):
        op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'seen_at')
    op.drop_column('messages', 'reply_to_id')
    op.drop_column('conversations', 'last_typing_at')
    # ### end Alembic commands ###
