"""Initial migration

Revision ID: fc37ea22d9bf
Revises: 
Create Date: 2025-06-30 15:30:39.665342

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fc37ea22d9bf'
down_revision = None
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    dialect = bind.dialect.name

    def table_exists(name: str) -> bool:
        return name in inspector.get_table_names()

    def has_column(table: str, column: str) -> bool:
        if not table_exists(table):
            return False
        return column in {col["name"] for col in inspector.get_columns(table)}

    def has_fk(table: str, columns: list, ref_table: str) -> bool:
        if not table_exists(table):
            return False
        for fk in inspector.get_foreign_keys(table):
            if fk.get("referred_table") == ref_table and fk.get("constrained_columns") == columns:
                return True
        return False

    op.execute('DROP TABLE IF EXISTS conversation_users')

    if not has_column('conversations', 'listing_id'):
        op.add_column('conversations', sa.Column('listing_id', sa.Integer(), nullable=True))
    if not has_column('conversations', 'renter_id'):
        op.add_column('conversations', sa.Column('renter_id', sa.Integer(), nullable=True))
    if not has_column('conversations', 'landlord_id'):
        op.add_column('conversations', sa.Column('landlord_id', sa.Integer(), nullable=True))

    if table_exists('conversations') and table_exists('users'):
        if has_column('conversations', 'renter_id') and not has_fk('conversations', ['renter_id'], 'users'):
            op.create_foreign_key(None, 'conversations', 'users', ['renter_id'], ['id'])
        if has_column('conversations', 'landlord_id') and not has_fk('conversations', ['landlord_id'], 'users'):
            op.create_foreign_key(None, 'conversations', 'users', ['landlord_id'], ['id'])
    if table_exists('conversations') and table_exists('listings'):
        if has_column('conversations', 'listing_id') and not has_fk('conversations', ['listing_id'], 'listings'):
            op.create_foreign_key(None, 'conversations', 'listings', ['listing_id'], ['id'])

    if not has_column('messages', 'conversation_id'):
        op.add_column('messages', sa.Column('conversation_id', sa.Integer(), nullable=True))
    if not has_column('messages', 'text'):
        op.add_column('messages', sa.Column('text', sa.String(), nullable=True))
    if not has_column('messages', 'is_approved'):
        op.add_column('messages', sa.Column('is_approved', sa.Boolean(), nullable=True))

    if dialect != "sqlite":
        try:
            op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
            op.drop_constraint(op.f('messages_receiver_id_fkey'), 'messages', type_='foreignkey')
            op.drop_constraint(op.f('messages_listing_id_fkey'), 'messages', type_='foreignkey')
        except Exception:
            pass

    if table_exists('messages') and table_exists('conversations'):
        if has_column('messages', 'conversation_id') and not has_fk('messages', ['conversation_id'], 'conversations'):
            op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    if table_exists('messages') and table_exists('users'):
        if has_column('messages', 'sender_id') and not has_fk('messages', ['sender_id'], 'users'):
            op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])

    if dialect != "sqlite":
        if has_column('messages', 'listing_id'):
            op.drop_column('messages', 'listing_id')
        if has_column('messages', 'receiver_id'):
            op.drop_column('messages', 'receiver_id')
        if has_column('messages', 'content'):
            op.drop_column('messages', 'content')

    if table_exists('tokens') and dialect != "sqlite":
        op.alter_column('tokens', 'user_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('messages', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_listing_id_fkey'), 'messages', 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_receiver_id_fkey'), 'messages', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'is_approved')
    op.drop_column('messages', 'text')
    op.drop_column('messages', 'conversation_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'landlord_id')
    op.drop_column('conversations', 'renter_id')
    op.drop_column('conversations', 'listing_id')
    op.create_table('conversation_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('conversation_users_conversation_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('conversation_users_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_users_pkey')),
    sa.UniqueConstraint('conversation_id', 'user_id', name=op.f('uix_conversation_user'))
    )
    # ### end Alembic commands ###
