"""Initial migration

Revision ID: fc37ea22d9bf
Revises: 
Create Date: 2025-06-30 15:30:39.665342

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fc37ea22d9bf'
down_revision = None
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_users')
    op.add_column('conversations', sa.Column('listing_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('renter_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('landlord_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'users', ['renter_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['landlord_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'listings', ['listing_id'], ['id'])
    op.add_column('messages', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('text', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_receiver_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_listing_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.drop_column('messages', 'listing_id')
    op.drop_column('messages', 'receiver_id')
    op.drop_column('messages', 'content')
    op.alter_column('tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('messages', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_listing_id_fkey'), 'messages', 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_receiver_id_fkey'), 'messages', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'is_approved')
    op.drop_column('messages', 'text')
    op.drop_column('messages', 'conversation_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'landlord_id')
    op.drop_column('conversations', 'renter_id')
    op.drop_column('conversations', 'listing_id')
    op.create_table('conversation_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('conversation_users_conversation_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('conversation_users_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_users_pkey')),
    sa.UniqueConstraint('conversation_id', 'user_id', name=op.f('uix_conversation_user'))
    )
    # ### end Alembic commands ###
